# -*- mode: ruby -*-
# vi: set ft=ruby :

require './vagrant-reload'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "arch-selinux" do |machine|
    # Use Arch Linux Vagrant Base box
    # https://wiki.archlinux.org/index.php/Vagrant#Base_Boxes_for_Vagrant
    machine.vm.box = "archlinux/archlinux"

    # SETools 4 requires more than 1024 MB of RAM
    machine.vm.provider :libvirt do |v|
      v.memory = 2048

      # Disable "Copy host CPU Configuration" to prevent the following KVM error on Intel CPUs:
      #   "the CPU is incompatible with host CPU: Host CPU does not provide required features: svm"
      #v.cpu_mode = "custom"
      #v.cpu_model = nil
    end
    machine.vm.provider :virtualbox do |v|
      v.memory = 2048
    end

    # Do not use a shared folder for packages, as VirtualBox shared folders
    # cause issues when using "install" files.
    machine.vm.synced_folder "..", "/srv/arch-selinux", type: "rsync",
      rsync__exclude: [".git/", "_vagrant/.vagrant/"]

    # Build and install packages and configure SELinux
    machine.vm.provision :shell, path: "step1_install_and_configure.sh"
    machine.vm.provision :reload
    # After the first reboot, relabel everything
    machine.vm.provision :shell, path: "step2_relabel.sh"
    # Reboot in a clean environment
    machine.vm.provision :reload
  end
end
