# -*- mode: ruby -*-
# vi: set ft=ruby :

require './vagrant-reload'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "arch-selinux" do |config|
    # Use Arch Linux Vagrant Base box
    # https://wiki.archlinux.org/index.php/Vagrant#Base_Boxes_for_Vagrant
    # https://github.com/terrywang/vagrantboxes/blob/master/archlinux-x86_64.md
    config.vm.box = "terrywang/archlinux"

    config.vm.synced_folder "..", "/srv/arch-selinux"

    # Build and install packages and configure SELinux
    config.vm.provision "shell", path: "step1_install_and_configure.sh"
    config.vm.provision :reload
    # After the first reboot, relabel everything
    config.vm.provision "shell", path: "step2_relabel.sh"
    # Reboot in a clean environment
    config.vm.provision :reload
  end
end
