#!/bin/bash

# Daemon to maintain path file context. 
# Uses inotify to look for creation of new files
# listed in the /etc/selinux/restorecond.conf file
# and restores the correct security context.

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in

   start)
     stat_busy "Starting restorecond"
     /usr/sbin/restorecond &>/dev/null
     if [ $? -ne 0 ]; then
       stat_fail
     else
       add_daemon restorecond
       stat_done
     fi
   ;;

   stop)
     stat_busy "Stopping restorecond"
     kill -9 `pidof /usr/sbin/restorecond` &>/dev/null
     rm_daemon smartd
     stat_done
   ;;

   restart)
     stat_busy "Restarting restorecond ..."
     $0 stop
     $0 start
     stat_done
   ;;

   *)
     echo "usage: $0 {start|stop|restart}"
esac
